#!/bin/bash

repoList=( $CIRCLE_REVERSE_DEPENDENCIES )

for repo in "${repoList[@]}"
do
	echo Triggering CI build $repo && \
	curl -v -X POST https://circleci.com/api/v1.1/project/github/redsift/$repo/tree/master?circle-token=$CIRCLE_TOKEN
done
