version: 2
jobs:
  container:
    environment:
      CONTAINER_NAME: quay.io/redsift/baseos
      CIRCLE_REVERSE_DEPENDENCIES: nodeos buildos-ubuntu javaos meteoros
      S6_V: v1.18.1.5
    docker:
      - image: cibuilds/docker:18.09.6
    steps:
      - checkout
      - setup_remote_docker
      - run: cd root; curl -k -L https://github.com/just-containers/s6-overlay/releases/download/$S6_V/s6-overlay-amd64.tar.gz | tar xz
      - run:
          command: |
            SHA="${CIRCLE_SHA1:0:7}"
            tagName=(${CIRCLE_BRANCH/-/ }) # release-1 => release
            export imageName=$CONTAINER_NAME:$SHA

            docker build -t $imageName .

            if [[ "$tagName" == "release" ]]; then
              echo "Tagging as $CONTAINER_NAME:latest"
              docker tag $imageName $CONTAINER_NAME:latest
            else
              echo "Tagging as $CONTAINER_NAME:beta"
              docker tag $imageName $CONTAINER_NAME:beta
            fi
      - run: docker login -u $QUAY_USER -p $QUAY_PASS quay.io
      - run: docker push $CONTAINER_NAME > /dev/null
      - run: ./circle_ci_trigger_build

workflows:
  version: 2
  build:
    jobs:
      - container:
          context: org-global